### ISSUE TITLE
🛂 [CoordinatorController] Implement POST "/users/interviewers"

### ISSUE THREAD

**Issue by Archasmiel** [CalculusEnjoyer/intellistart-java-2022-vanquishers#64]

**Comment by CalculusEnjoyer** [comment]
02.11:
Implemented all of the assigned endpoints except _delete_ endpoint. 
Going to finish _delete_ endpoint, write tests and make a PR.

**Comment by CalculusEnjoyer** [comment]
03.11 - 04.11
Implemented all endpoints that were assigned to me, wrote tests, and made a PR
Realized that it would be much better to make small PRs for every endpoint, because it really would be easier to review, so going to make PRs in a such way next time.

Going to make a utility class for populating fields and refactor my code in the update booking endpoint, where I manually set all fields that have to be updated.
